### ISSUE TITLE
Autenticação Open ID

### ISSUE THREAD

**Issue by jpmehl** [ethymos/delibera#11]
Aqui entramos em um debate mais amplo, das redes federadas. Nossa proposta é permitir que se aproveitem os usuários de outras plataformas para facilitar o cadastro e a integração entre diferentes redes.

**Comment by jacsonp** [comment]
Concordo com o Leo, esse não é o papel do plugin e sim da plataforma, embora ele implemente algumas funcionalidades fora do seu escopo, mas com objetivo de fluxo. Acredito que com a instalação do plugin https://github.com/redelivre/wp-opauth esse problema seja resolvido, não precisando que o delibera faça o papel, o que você @jpmehl podemos fechar esse aqui?

**Comment by jacsonp** [comment]
This issue was moved to redelivre/delibera#33
