### ISSUE TITLE
Possibilidades adicionais de interação

### ISSUE THREAD

**Issue by jpmehl** [ethymos/delibera#12]
Já temos um estudo inicial feito pelo Sivaldo, que vai junto a uma nova proposta de organização de conteúdo, precisamos debater bastante isto para não investirmos tempo desnecessário.

![delibera-wireframe-discussao_COMMENTS SIVALDO](https://f.cloud.github.com/assets/4163139/383016/4e9e4c56-a609-11e2-827d-a964cf4b1ca8.jpg)

**Comment by jacsonp** [comment]
This issue was moved to redelivre/delibera#34
