### ISSUE TITLE
Melhorias na interface de relatoria

### ISSUE THREAD

**Issue by rodrigoprimo** [ethymos/delibera#25]
Estamos pensando em fazer algumas melhorias na tela de relatoria de uma pauta. Gostaríamos de ter uma maneira de mudar o status dos encaminhamentos que foram usados pelo relator para criar um terceiro. Talvez a gente não esteja entendendo alguma, mas achamos estranho os encaminhamentos usados como base para um outro irem também para a votação. Achávamos que apenas o encaminhamento criado pelo relator que iria para votação e os outros ficariam acessíveis apenas para manter o histórico. Além disso, pensamos em mudar uma pouco a interface para facilitar o processo de escolha do relator de quais encaminhamentos devem ir para votação. O Anderson está trabalhando numa tela e em breve devemos ter alguma coisa para apresentar.

**Comment by jpmehl** [comment]
@rodrigoprimo você lembra se avançaram nisto? É uma demanda prioritária e pretendemos colocar na pauta no próximo período.

**Comment by rodrigoprimo** [comment]
Não lembro.

**Comment by jacsonp** [comment]
This issue was moved to redelivre/delibera#39
