### ISSUE TITLE
Funções que não são mais utilizadas

### ISSUE THREAD

**Issue by rodrigoprimo** [ethymos/delibera#26]
Jacson,

Acho que encontrei duas funções que não são mais utilizadas no delibera.php:

- delibera_tiracento()
- delibera_slug_under()

Podemos remover?

Talvez vocês já tenham visto mas o Wordpress tem uma função para remover os acentos das strings remove_accents().

**Comment by jacsonp** [comment]
This issue was moved to redelivre/delibera#40
