### ISSUE TITLE
Erro na diferenciacao entre opinioes, encaminhamentos e suas respostas

### ISSUE THREAD

**Issue by stamato** [ethymos/delibera#29]
Pessoal, no delibera, quando criamos uma opiniao ou encaminhamento e fazemos um comentario ou resposta, essas se tornam como se fosse um novo tópico (nova opiniao ou encaminhamento). Ou seja, a resposta de uma opiniao/encam. nao fica diretamente vinculada ao que se quis responder e fica registrada como se fosse um topico novo. Dessa forma, todas as publicacoes, sejam elas opinioes, propostas novas ou respostas ä uma já feita, ficam jogadas sem diferenciacao aparente ao usuario, o que pode gerar confusao.

Para entender melhor,vejam o link: http://ciclodeculturadigital.redelivre.org.br/pauta/taller-en-bogota

**Comment by jacsonp** [comment]
This issue was moved to redelivre/delibera#42
