### ISSUE TITLE
Problemas na etapa relatoria

### ISSUE THREAD

**Issue by stamato** [ethymos/delibera#30]
Quando estamos em relatoria, no tema creta, nao se consegue forcar o fim do prazo para o periodo de relatoria. 

No tema atenas se consegue forcar, mas todas as propostas vao para votacao, nao permitindo ao adm selecionar as que irao ser votadas. Existem as checkbox onde se escolhe quais serao votadas, mas nao existe um botao que salva essas configuracoes e o sistema leva todas pra votacao.

**Comment by jacsonp** [comment]
This issue was moved to redelivre/delibera#43
