### ISSUE TITLE
Modificação no sistema de temas do delibera

### ISSUE THREAD

**Issue by marcoamarelo** [ethymos/delibera#35]
Quero abrir um debate sobre o gerenciamento de temas do delibera. O formato atual não permite a separação entre visual e o código do plugin. Eu acredito que o delibera deveria trabalhar com base num conjunto de templates próprios, mas que esses deveriam estar no próprio código do tema. Podemos colocar alguns códigos de exemplo e orientar o usuário a copiar para o seu código do tema, mas acho que devemos abolir a ideia de selecionar um tema específico pro delibera.

**Comment by marcoamarelo** [comment]
Acredito que a possibilidade de colocar os arquivos de tema do delibera dentro do tema já resolve o problema. Talvez a questão da seleção não seja um problema. Acho por bem fechar essa issue.

**Comment by jacsonp** [comment]
Precisamos criar um manual do plugin para desenvolvedores de tema, podemos derivar outra issue para tanto.

**Comment by marcoamarelo** [comment]
Acho massa a Ideia Jacson. Acho inclusive que poderiamos concentrar tudo no
Readme.
Em 15/04/2015 1:13 PM, "Jacson" <notifications@github.com> escreveu:

**Comment by juliovedovatto** [comment]
Boa Tarde. 

Preferem que modificações sejam enviadas aqui (por meio de git clone) ou que seja gerado um fork? Peguei o Desafio 2 do edital.

[]'s

**Comment by jacsonp** [comment]
Pull request no fork da redelivre, obrigado

**Comment by juliovedovatto** [comment]
Criado pull request no fork redelivre. No aguardo de feedback.

**Comment by diegorojas** [comment]
Ei Galera beleza? Precisamos de uma decisão rápida aqui. 

Pelo que vi seguiram-se dois caminhos de documentação, têm um wiki rolando até dez/15:
https://github.com/redelivre/delibera/wiki

E têm uma indicação na issue aqui de seguir a documentação no Readme file mesmo, alterado ontem.

O que acreditam ser melhor padronizar como documentação do delibera? Acho que manter os dois completos é ruim, mas manter o Readme como um "índice geral" pode ser uma ótima.

Ai podemos manter tudo de denso no wiki e introduções e links no Readme. O que acham?

**Comment by jacsonp** [comment]
This issue was moved to redelivre/delibera#45
