### ISSUE TITLE
Ajuste em massa da data limite de discussão de pauta

### ISSUE THREAD

**Issue by marcoamarelo** [ethymos/delibera#37]
Permitir o ajuste em massa a data limite de discussão.

**Comment by jpmehl** [comment]
Não seria melhor aproveitar e criar um esquema de edição em massa das
cinfiguracoes da pauta?
Em 30/01/2015 00:42, "marcoamarelo" <notifications@github.com> escreveu:

**Comment by marcoamarelo** [comment]
Acho que estamos falando da mesma coisa João. A ideia é que na lista de pautas, possa-se selecionar as pautas que se quer alterar e definir um novo prazo para a situação de pauta.

**Comment by marcoamarelo** [comment]
Issue resolvida com o commit 99b7f85fd92ae334ade8753502c7963d8a80d6f6
