### ISSUE TITLE
Upload de arquivos na criação de pautas

### ISSUE THREAD

**Issue by marcoamarelo** [ethymos/delibera#38]
O delibera precisa suportar o upload de arquivos na criação de pautas, pois essa também é uma forma dos colaboradores contribuirem para o debate.

**Comment by jpmehl** [comment]
Esta funcionalidade existia originalmente no comentário, onde o usuário
poderia inserir um arquivo no seu comentário, mas foi descontinuada por ser
um plugin externo ao delibera.
Também é possível que ele faça upload ao criar a proposta no backend.
Então acho que poderia ser pensada uma solução que permitisse uploads tanto
na criação de pauta no frontend quanto nos comentário.

Em 26 de março de 2015 12:08, marcoamarelo <notifications@github.com>
escreveu:

> O delibera precisa suportar o upload de arquivos na criação de pautas,
> pois essa também é uma forma dos colaboradores contribuirem para o debate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ethymos/delibera/issues/38>.
>



-- 
João Paulo Mehl
Ethymos Soluções em Web
www.ethymos.com.br
(41)3077-4163 / 9627-5518

**Comment by marcoamarelo** [comment]
Let's do it ;-)

**Comment by jacsonp** [comment]
This issue was moved to redelivre/delibera#46
