### ISSUE TITLE
Sistemas de votação diferenciados

### ISSUE THREAD

**Issue by jpmehl** [ethymos/delibera#4]
É preciso definir novas formas de votação e viabilizar a implementação no sistema. 
Ex: colocar uma proposta contra outra / escolher uma ordem de 3 prioritárias

**Comment by lpirola** [comment]
@jacsonp @jpmehl a forma atual de votação consiste em curtir e discordar a pauta?

**Comment by jpmehl** [comment]
Salve lucas, o concordar e discordar é só uma forma de mensuração da temperatura do debate e da relevancia do comentario. 
A votação só ocorre no final do processo. 
Sugiro que crie uma instalação do delibera e siga todos os processos, criando um conjubto de propostas. Você vai perceber que quando chegar na fase de votação,  aparecerá uma lista de todas as propostas e você poderá escolher mais de uma. 
Este desafio vai no sentido de apresentar uma outra forma pra votação,  permitindo que se coloque uma proposta contra outra, por exemplo. 
Destacando que o objetivo do desafio é que seja uma solução simples.

**Comment by cabelotaina** [comment]
Meu desafio:

![image](https://cloud.githubusercontent.com/assets/1827173/12325783/c36f7d18-bab3-11e5-8ccf-26ee0209b6b7.png)

vou explicar o que fiz e quero saber se entendi bem o desafio.

No ciclo de vida de uma pauta ela passa por proposta de pauta, pauta (submissão de proposta de encaminhamento), relatória, votação nas propostas de encaminhamento. Atualmente no processo de votação das propostas de encaminhamento eu modifiquei a visão para usar radio, ao invés de checkbox,permitindo votar em apenas um proposta de encaminhamento. Criei uma configuração universal do delibera que permite um usuário administrador forçar todas as pautas serem por votação simples. E venho tentando criar uma configuração individual onde o usuário define se a pauta é por votação simples ou não, o que esta sendo o mais custoso ate aqui. Ainda vou fazer a validação de erro e de tentativa seleção de mais de uma proposta de encaminhamento. Por fim vou manter a votação padrão, onde se pode votar em mais que uma propostas de encaminhamento.

Veja como esta a visão:

![image](https://cloud.githubusercontent.com/assets/1827173/12325924/bb095940-bab4-11e5-977a-2d50e644804a.png)

![image](https://cloud.githubusercontent.com/assets/1827173/12325961/ebecf102-bab4-11e5-9b9c-8863209ad0de.png)

![image](https://cloud.githubusercontent.com/assets/1827173/12325817/f6d45a02-bab3-11e5-8dc6-f8dbdf220772.png)

Minha principal duvida esta como o delibera esta permitindo o envio dos metadados durante o salvamento do post. Notei ate aqui que o arquivo que possui essas configurações, bem como outras, é o delibera.php.  No entanto o $_POST não recebe o meu metadado.

Espero estar no caminho certo. Obrigado.

**Comment by jacsonp** [comment]
Parece estar ficando legal, gostaria que a opção de votação fosse um dropdown, pois haverá mais opções, visto o que descreve a issue.
Os dados são salvos na função delibera_save_post, e a função que exibe as opções é a delibera_pauta_meta, não tem muito segredo, quem gera o formulário e faz o postback é o WordPress, tendo um id e um name em uma tag input tem que aparecer na $_POST. Não esqueça de criar uma entrada padrão na função principal de configuração para a nova opção (delibera_get_main_config, no arquivo delibera_conf.php).

**Comment by jacsonp** [comment]
This issue was moved to redelivre/delibera#27
