### ISSUE TITLE
Erro na ativação do plugin em Wordpress 4.1.1

### ISSUE THREAD

**Issue by tatianegonzaga** [ethymos/delibera#40]
Oi Amarelo

Acabei de instalar o plugin no WordPress 4.1.1 e no momento da ativação, retorna o erro:
Não foi possível ativar o plugin porque ele gerou um erro fatal.
Parse error: syntax error, unexpected T_FUNCTION in /home/forumleitura/public_html/wp-content/plugins/delibera/delibera.php on line 3173

Existe alguma correção para esse bug?

Valeu ;) 
Abraços, Tati

**Comment by jacsonp** [comment]
Ola Tatiane, gostaria de saber qual a versão do delibera que você está usando? É a ultima do master? Porque nem sequer tem esse linha na minha versão.

**Comment by tatianegonzaga** [comment]
Oi Jacson, eu segui esse procedimento: http://culturadigital.br/plataformascolaborativas/delibera-democracia-digital/instalacao, versão 1.0.3

**Comment by jacsonp** [comment]
A versão 1.03, era para estar no link:
https://github.com/ethymos/delibera/archive/1.0.3.zip
Pode tentar também a ultima versão estável usada na redelivre:
https://github.com/ethymos/delibera/archive/cb286bbf5a9baa39fa7a91602ad537a4a3d89c02.zip
Ou a ultima versão: https://github.com/ethymos/delibera/archive/master.zip

**Comment by tatianegonzaga** [comment]
Então, baxei aqui do master, vou instalar agora para ver ;)
Obrigada

**Comment by tatianegonzaga** [comment]
Agora retorna esse erro: 
Parse error: syntax error, unexpected T_FUNCTION in /home/forumleitura/public_html/wp-content/plugins/delibera/delibera_widgets.php on line 50

**Comment by tatianegonzaga** [comment]
Vou tentar com a versão da redelivre, já te aviso se deu certo.

**Comment by tatianegonzaga** [comment]
Versão da redelivre retornou o mesmo erro: 
Parse error: syntax error, unexpected T_FUNCTION in /home/forumleitura/public_html/wp-content/plugins/delibera/delibera_widgets.php on line 50

**Comment by jacsonp** [comment]
Mesmo erro, arquivo diferente, consegui rastrear agora, o delibera requerer a versão 5.3 do php no mínimo. Pode ver se consegue atualizar o php?

**Comment by tatianegonzaga** [comment]
Ok, vou instalar no meu outro server que é php 5.4 ;)
Obrigada Jacson
