### ISSUE TITLE
Como ver as pautas?

### ISSUE THREAD

**Issue by interstar** [ethymos/delibera#43]
Instalei a versão atual deste repo. Adicionei um pauta mas não vi nada no blog.

Como ver as pautas?

**Comment by jpmehl** [comment]
Ele cria um /pautas,  vc testou?
Qual tua implementação?
Em 25/07/2015 17:26, "phil jones" <notifications@github.com> escreveu:

**Comment by jacsonp** [comment]
é um post type, ou seja, se estiver com o permalink ativo (mod rewrite), você poderá acessar em /pauta se não, tem que passar a query: ?post_type=pauta

**Comment by interstar** [comment]
Obrigado. Estou conseguindo ver como @jacsonp sugeriu. post_type=pauta.
