### ISSUE TITLE
Visualidade de comentários atrelados está bugado.

### ISSUE THREAD

**Issue by anapaulabrasa** [ethymos/delibera#46]
No tema Atena, para o usuário que está deslogado, a visualidade de comentários atrelados a outros (uma opinião/comentário/encaminhamento respondendo ou ligada diretamente a outra) está bugado, vide a imagem abaixo

![bugencaminhamentoatrelado](https://cloud.githubusercontent.com/assets/2422926/10942417/33fe01a2-82f7-11e5-9e74-ee2628477669.png)

**Comment by jacsonp** [comment]
preciso saber em qual tema do wordpress o delibera foi aplicado, assim como tema do delibera usado

**Comment by anapaulabrasa** [comment]
Tema Público. Tema atenas.
